import 'package:freezed_annotation/freezed_annotation.dart';

import 'detailed_params.dart';
import 'discounts.dart';
import 'main_pair.dart';

part 'product.freezed.dart';
part 'product.g.dart';

@freezed
class Product with _$Product {
  factory Product({
    required String productId,
    required String product,
    required String companyName,
    required String productType,
    required String parentProductId,
    required String productCode,
    required String status,
    required String companyId,
    required String listPrice,
    required int amount,
    required String weight,
    required String length,
    required String width,
    required String height,
    required String shippingFreight,
    required String lowAvailLimit,
    required String timestamp,
    required String updatedTimestamp,
    required String usergroupIds,
    required String isEdp,
    required String edpShipping,
    required String unlimitedDownload,
    required String tracking,
    required String freeShipping,
    required String zeroPriceAction,
    required String isPbp,
    required String isOp,
    required String isOper,
    required String isReturnable,
    required String returnPeriod,
    required String availSince,
    required String outOfStockActions,
    required String localization,
    required String minQty,
    required String maxQty,
    required String qtyStep,
    required String listQtyCount,
    required String taxIds,
    required String ageVerification,
    required String ageLimit,
    required String optionsType,
    required String exceptionsType,
    required String detailsLayout,
    required String shippingParams,
    required String facebookObjType,
    required String buyNowUrl,
    required String unitsInProduct,
    required String showPricePerXUnits,
    required String price,
    required String metaKeywords,
    required String metaDescription,
    required dynamic searchWords,
    required dynamic promoText,
    required String unitName,
    required List<int> categoryIds,
    required String seoName,
    required String seoPath,
    required int mainCategory,
    required dynamic optionsTypeRaw,
    required dynamic exceptionsTypeRaw,
    required dynamic trackingRaw,
    required dynamic zeroPriceActionRaw,
    required dynamic minQtyRaw,
    required dynamic maxQtyRaw,
    required dynamic qtyStepRaw,
    required dynamic listQtyCountRaw,
    required String detailsLayoutRaw,
    required List<dynamic> variationFeatures,
    required MainPair mainPair,
    required String basePrice,
    required dynamic selectedOptions,
    required bool hasOptions,
    required dynamic productOptions,
    required Discounts discounts,
    required List<dynamic> qtyContent,
    required DetailedParams detailedParams,
    required String imageUrl,
    required String companyLogo,
    required bool allowAddToCart,
    required bool allowPostReview,
    required String formatPrice,
    required String formatListPrice,
    required String formatBasePrice,
    required int ecRewardPoints,
    required dynamic variationFeatureCollection,
    required dynamic productFeatures,
    required bool allowChat,
    required String chatThreadId,
  }) = _Product;

  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);
}
