import 'package:freezed_annotation/freezed_annotation.dart';

part 'user_data_entity.freezed.dart';
part 'user_data_entity.g.dart';

@freezed
abstract class UserDataEntity with _$UserDataEntity {
  factory UserDataEntity({
    String? userId,
    String? status,
    String? userType,
    String? userLogin,
    String? referer,
    String? isRoot,
    String? companyId,
    String? lastActivity,
    String? timestamp,
    String? password,
    String? salt,
    String? firstname,
    String? lastname,
    String? company,
    String? email,
    String? phone,
    String? fax,
    String? url,
    String? taxExempt,
    String? langCode,
    String? birthday,
    String? purchaseTimestampFrom,
    String? purchaseTimestampTo,
    String? responsibleEmail,
    String? passwordChangeTimestamp,
    String? apiKey,
    String? helpdeskUserId,
    String? janrainIdentifier,
    String? profileId,
    String? profileType,
    String? bFirstname,
    String? bLastname,
    String? bAddress,
    String? bAddress2,
    String? bCity,
    String? bCounty,
    String? bState,
    String? bCountry,
    String? bZipcode,
    String? bPhone,
    String? sFirstname,
    String? sLastname,
    String? sAddress,
    String? sAddress2,
    String? sCity,
    String? sCounty,
    String? sState,
    String? sCountry,
    String? sZipcode,
    String? sPhone,
    String? sAddressType,
    String? profileName,
    String? profileUpdateTimestamp,
    List<dynamic>? fields,
    String? bCountryDescr,
    String? sCountryDescr,
    String? bStateDescr,
    String? sStateDescr,
    int? points,
  }) = _UserDataEntity;

  factory UserDataEntity.fromJson(Map<String, dynamic> json) =>
      _$UserDataEntityFromJson(json);
}
