// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_data_entity.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_UserDataEntity _$UserDataEntityFromJson(Map<String, dynamic> json) =>
    _UserDataEntity(
      userId: json['user_id'] as String?,
      status: json['status'] as String?,
      userType: json['user_type'] as String?,
      userLogin: json['user_login'] as String?,
      referer: json['referer'] as String?,
      isRoot: json['is_root'] as String?,
      companyId: json['company_id'] as String?,
      lastActivity: json['last_activity'] as String?,
      timestamp: json['timestamp'] as String?,
      password: json['password'] as String?,
      salt: json['salt'] as String?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      company: json['company'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      fax: json['fax'] as String?,
      url: json['url'] as String?,
      taxExempt: json['tax_exempt'] as String?,
      langCode: json['lang_code'] as String?,
      birthday: json['birthday'] as String?,
      purchaseTimestampFrom: json['purchase_timestamp_from'] as String?,
      purchaseTimestampTo: json['purchase_timestamp_to'] as String?,
      responsibleEmail: json['responsible_email'] as String?,
      passwordChangeTimestamp: json['password_change_timestamp'] as String?,
      apiKey: json['api_key'] as String?,
      helpdeskUserId: json['helpdesk_user_id'] as String?,
      janrainIdentifier: json['janrain_identifier'] as String?,
      profileId: json['profile_id'] as String?,
      profileType: json['profile_type'] as String?,
      bFirstname: json['b_firstname'] as String?,
      bLastname: json['b_lastname'] as String?,
      bAddress: json['b_address'] as String?,
      bAddress2: json['b_address2'] as String?,
      bCity: json['b_city'] as String?,
      bCounty: json['b_county'] as String?,
      bState: json['b_state'] as String?,
      bCountry: json['b_country'] as String?,
      bZipcode: json['b_zipcode'] as String?,
      bPhone: json['b_phone'] as String?,
      sFirstname: json['s_firstname'] as String?,
      sLastname: json['s_lastname'] as String?,
      sAddress: json['s_address'] as String?,
      sAddress2: json['s_address2'] as String?,
      sCity: json['s_city'] as String?,
      sCounty: json['s_county'] as String?,
      sState: json['s_state'] as String?,
      sCountry: json['s_country'] as String?,
      sZipcode: json['s_zipcode'] as String?,
      sPhone: json['s_phone'] as String?,
      sAddressType: json['s_address_type'] as String?,
      profileName: json['profile_name'] as String?,
      profileUpdateTimestamp: json['profile_update_timestamp'] as String?,
      fields: json['fields'] as List<dynamic>?,
      bCountryDescr: json['b_country_descr'] as String?,
      sCountryDescr: json['s_country_descr'] as String?,
      bStateDescr: json['b_state_descr'] as String?,
      sStateDescr: json['s_state_descr'] as String?,
      points: (json['points'] as num?)?.toInt(),
    );
