import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:meat_empire/src/features/products/domain/product_details_response/product_options/product_options.dart';
import 'package:meat_empire/src/features/products/domain/product_details_response/variation_feature/variation_feature.dart';

import '../product/discounts.dart';
import '../product/main_pair.dart';
import 'detailed_params.dart';
import 'product_reviews_avail_sorting.dart';
import 'product_reviews_search.dart';
import 'product_reviews_sorting.dart';

part 'product_details.freezed.dart';
part 'product_details.g.dart';

@freezed
class ProductDetails with _$ProductDetails {
  factory ProductDetails({
    required int minItemsInBox,
    required int maxItemsInBox,
    required int boxLength,
    required int boxWidth,
    required int boxHeight,
    required int productId,
    required String productCode,
    required String productType,
    required String status,
    required String companyId,
    required String listPrice,
    required int amount,
    required String weight,
    required String length,
    required String width,
    required String height,
    required String shippingFreight,
    required String lowAvailLimit,
    required String timestamp,
    required String updatedTimestamp,
    required String usergroupIds,
    required String isEdp,
    required String edpShipping,
    required String unlimitedDownload,
    required String tracking,
    required String freeShipping,
    required String zeroPriceAction,
    required String isPbp,
    required String isOp,
    required String isOper,
    required String isReturnable,
    required String returnPeriod,
    required String availSince,
    required String outOfStockActions,
    required String localization,
    required String minQty,
    required String maxQty,
    required String qtyStep,
    required String listQtyCount,
    required List<dynamic> taxIds,
    required String ageVerification,
    required String ageLimit,
    required String optionsType,
    required String exceptionsType,
    required String detailsLayout,
    required String shippingParams,
    required String facebookObjType,
    required String parentProductId,
    required String buyNowUrl,
    required String unitsInProduct,
    required String showPricePerXUnits,
    required String langCode,
    required String product,
    required String shortname,
    required dynamic shortDescription,
    required String fullDescription,
    required String metaKeywords,
    required String metaDescription,
    required dynamic searchWords,
    required String pageTitle,
    required dynamic ageWarningMessage,
    required dynamic promoText,
    required String unitName,
    required String price,
    required List<int> categoryIds,
    required String popularity,
    required String companyName,
    required String? salesAmount,
    required String seoName,
    required String seoPath,
    required dynamic pointPrice,
    required String? discussionType,
    required dynamic averageRating,
    required dynamic productReviewsCount,
    required String basePrice,
    required int mainCategory,
    required List<dynamic> imagePairs,
    required MainPair mainPair,
    required String sharedProduct,
    required List<dynamic> productFeatures,
    required List<dynamic> headerFeatures,
    required dynamic optionsTypeRaw,
    required dynamic exceptionsTypeRaw,
    required dynamic trackingRaw,
    required dynamic zeroPriceActionRaw,
    required dynamic minQtyRaw,
    required dynamic maxQtyRaw,
    required dynamic qtyStepRaw,
    required dynamic listQtyCountRaw,
    required String detailsLayoutRaw,
    required DetailedParams detailedParams,
    required List<String> sharedBetweenCompanies,
    required String haveRequired,
    required List<VariationFeature> variationFeatures,
    required dynamic selectedOptions,
    required bool hasOptions,
    required ProductOptions? productOptions,
    required Discounts discounts,
    required List<dynamic> qtyContent,
    required String imageUrl,
    required String companyLogo,
    required bool allowAddToCart,
    required bool allowPostReview,
    required String formatPrice,
    required String formatListPrice,
    required String formatBasePrice,
    required int ecRewardPoints,
    required List<dynamic> attachments,
    required List<String> imageUrls,
    required List<dynamic> additionalImages,
    required String websiteUrl,
    required List<dynamic> productReviews,
    required List<dynamic> productReviewsRatingStats,
    required ProductReviewsSearch productReviewsSearch,
    required List<ProductReviewsSorting> productReviewsSorting,
    required List<String> productReviewsSortingOrders,
    required ProductReviewsAvailSorting productReviewsAvailSorting,
    required dynamic variationFeatureCollection,
    required bool allowChat,
    required String chatThreadId,
  }) = _ProductDetails;

  factory ProductDetails.fromJson(Map<String, dynamic> json) =>
      _$ProductDetailsFromJson(json);
}
